import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        <footer className="flex items-center justify-center p-4 text-xs">
          <Link
            href="https://www.dominikrubroeder.dev"
            className="text-muted-foreground"
            target="_blank"
          >
            dominikrubroeder.dev
          </Link>
        </footer>
      </body>
    </html>
  );
}
